disquaire_project/disquaire_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
]

disquaire_project/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='home'),
    path('list/', views.listing, name='listing'),
    path('<int:id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
]

disquaire_project/store/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Album(models.Model):
    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()
    artiste = models.ManyToManyField(Artist, related_name='albums', blank=True)

    def __str__(self):
        return self.title

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted = models.BooleanField(default=False)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    album = models.OneToOneField(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.contact.name

disquaire_project/store/forms.py
from django import forms
from .models import Artist, Album, Booking

class SearchForm(forms.Form):
    query = forms.CharField()

disquaire_project/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Artist, Contact, Booking
from .forms import SearchForm
from django.contrib.postgres.search import SearchQuery, SearchRank


# Create your views here.
def index(request):
    albums = Album.objects.filter(available=True).order_by('created_at')[:3]
    return render(request, 'index.html', {'albums': albums})


def listing(request):
    albums = Album.objects.filter(available=True)[:6]
    context = {
        'albums': albums,
    }
    return render(request, 'store/list.html', context)


def detail(request, id):
    album = get_object_or_404(Album, id=id)
    artists = " ".join([artist.name for artist in album.artiste.all()])
    context = {
        'album_title': album.title,
        'artists': artists,
        'album_id': album.id,
        'thumbnail': album.picture,
    }
    return render(request, 'store/detail.html', context)


def search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_query = SearchQuery(query)
            results = Album.annotate(rank=SearchRank(search_query))

    context = {
        'form': form,
        'query': query,
        'results': results,
    }
    return render(request, 'store/search.html', context)

disquaire_project/store/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Le Disquaire des gignoles</title>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="{% static 'store/css/business-casual.css' %}" rel="stylesheet">
</head>

<body>

    <div class="brand">Bateaux Pirates</div>
    <div class="address-bar">The Plaza | 5483 Crochet Whisky Ave. | La Rochelle, France 69 | 555.519.2013</div>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'store:home' %}">Home</a></li>
                    <li><a href="{% url 'store:listing' %}">Lists</a></li>
                    <li><a href="#">Réservations</a></li>
                    <li>
                        <a>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><strong>RECHERCHER BATEAUX</strong></button>
                        </form>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="img/slide-1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-3.jpg" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2>
                        <small>Welcome to</small>
                    </h2>
                    <h1>
                        <span class="brand-name">Bateaux Pirates</span>
                    </h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By <strong>Capitain Mister Pan</strong></small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center"><strong>Bateaux à la mode</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="img/intro-pic.jpg" alt="">
                    <hr class="visible-xs">
                </div>
                <div class="box">
                    {% for album in albums %}
                    <div class ="col-sm-4 text-center">
                        <a href="{% url 'store:detail' album.id %}">
                        <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
                        </a>
                        <h3><a href="{% url 'store:detail' album.id %}">{{ album.title }}</a></h3>
                        {% for artist in album.artists.all %}
                            <p>{{ artist.name }}</p>
                        {% endfor %}
                    </div>
                    {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center"><strong>Les voilliers de la nuits</strong>
                    </h2>
                    <hr>
                </div>
                <div class="box">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Company 2020</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->
    <script src="{% static 'store/js/jquery.js' %}"></script>
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>
    <script>
    // Activates the Carousel
    $('.carousel').carousel({
        interval: 5000
    })
    </script>

</body>

</html>

disquaire_project/store/templates/store/detail.html
{% extends 'index.html' %}

{% block content %}
<hr>
<h1 class="intro-text text-center">{{ album_title }}</h1>
<hr class="detail-separator">
<div class="col-md-6">
  <img src="{{ thumbnail }}" alt="{{ album_title }}" class="img-responsive">
</div>
<div class="col-md-6">
  <div style="margin-bottom:45px">
    <h2 class="text-center artist_name">Artistes</h2>
    <p>{{ artists_name }}</p>
  </div>

  <h2 class="text-center artist_name">Réserver {{ album_title }}</h2>
  <p style="margin-bottom: 20px;">Demandez-nous de mettre de côté {{ album_title }} et venez le chercher dès demain en magasin ! </p>
  <form class="form-inline" action="" method="post">
    {% csrf_token %}
    <div class="form-group {% if form.name.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.name.id_for_label }}" class="control-label">Nom</label>
      {{ form.name }}
    </div>
    <div class="form-group {% if form.email.errors %}has-warning has-feedback{% endif %}">
      <label for="{{ form.email.id_for_label }}" class="control-label">E-mail</label>
      {{ form.email }}
    </div>
    <input type="hidden" class="hidden" value="{{ album_id }}" name="album_id">

    <button type="submit" class="btn btn-success">Réserver</button>
  </form>
  {% if errors %}
    <div>
      {% for key, error in errors %}
        {% autoescape off %}
          {{ error }}
        {% endautoescape %}
      {% endfor %}
    </div>
  {% endif %}


</div>


{% endblock %}

disquaire_project/store/templates/store/list.html
{% extends 'index.html' %}
{% block content %}

{% for album in albums %}
<div class ="col-sm-4 text-center">
    <a href="{% url 'store:detail' album.id %}">
    <img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
    </a>
    <h3><a href="{% url 'store:detail' album.id %}">{{ album.title }}</a></h3>
    {% for artist in album.artists.all %}
        <p>{{ artist.name }}</p>
    {% endfor %}
</div>
{% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}

{% endfor %}

{% endblock %}

disquaire_project/store/templates/store/search.html
{% extends 'index.html' %}
{% block content %}

{% endblock %}